/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clever.bank;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    App classUnderTest = new App();
    @Test void appHasAGreeting() {
        
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void ifSumToAddRight() {
       Account ac = new Account("AA89 KLMN 9999 4554 DABC 778A 9876", "9871237612", "2009-10-12", "2027-10-12");
       ac.setBalance(384.99);
       Transaction tr = new Transaction();
       Assertions.assertThrows(IllegalArgumentException.class, ()->{
            tr.topUp(ac, 15.55);
        });
    }

    @Test
    void ifSumToSubstractRight() {
       Account ac = new Account("AA89 KLMN 9999 4554 DABC 778A 9876", "9871237612", "2009-10-12", "2027-10-12");
       ac.setBalance(384.99);
       Transaction tr = new Transaction();
       Assertions.assertThrows(IllegalArgumentException.class, ()->{
            tr.withdraw(ac, 500.55);
        });
    }

    @Test
    void isTransferright(){
        Account ac = new Account("AA89 KLMN 9999 4554 DABC 778A 9876", "9871237612", "2009-10-12", "2027-10-12");
       ac.setBalance(384.99);
       Transaction tr = new Transaction();
       Assertions.assertThrows(IllegalArgumentException.class, ()->{
            tr.isEnough(ac, 500.55);
        });
    }

}
